sudo: required 
services:
  - docker

before_install:
  - docker build -t talhatylextech/docker-reacttest -f Dockerfile.dev .
  
script:
 - docker run -e CI=true talhatylextech/docker-reacttest  npm run test -- --coverage

